export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EDIT_ARTICLE_IN_CART_NUMBER = "EDIT_ARTICLE_IN_CART_NUMBER";
export const ADD_TO_SUB_TOTAL = "ADD_TO_SUB_TOTAL";
export const REMOVE_DATA_FROM_CART_AND_SUBTOTAL = "REMOVE_DATA_FROM_CART_AND_SUBTOTAL"